Rework *.msgids handling when neither client nor server stubs are required
Originally added in commit 255c47e669819f153c722c98a230f6fe4e6ece08, but "make
distcheck" didn't like that:

    [...]
    ERROR: files left in build directory after distclean:
    ./ipc/notify.msgids
    Makefile:7489: recipe for target 'distcleancheck' failed
    make[1]: *** [distcleancheck] Error 1
    make[1]: Leaving directory '[...]/gnumach/release.build/gnumach-1.5/_build/sub'
    Makefile:7416: recipe for target 'distcheck' failed
    make: *** [distcheck] Error 1

Instead of special-casing that, generalize the Makefile rules.

	* Makefrag.am (nodist_lib_dep_tr_for_defs_a_SOURCES): Add
	ipc/notify.none.defs.c.
	(nodist_libkernel_a_SOURCES): Add ipc/notify.none.msgids.
	(gnumach.msgids): Remove ipc/notify.msgids prerequisite.
	* Makerules.mig.am (%.msgids): Remove rule, and instead...
	(%.none.defs.c, %.none.msgids): ... add these rules.