Resurrect x86-linux build.
This avoids using system headers, which may result in

    kern/strings.c: In function 'strchr':
    kern/strings.c:188:32: error: 'NULL' undeclared (first use in this function)

    In file included from util/atoi.c:77:
    ./util/atoi.h:65:29: error: unknown type name 'u_char'

    device/net_io.c: In function 'bpf_do_filter':
    device/net_io.c:1636:34: error: 'u_int' undeclared (first use in this function); did you mean 'int'?

    In file included from device/subrs.c:36:
    ./device/if_ether.h:43:9: error: unknown type name 'u_char'
       43 |         u_char  ether_dhost[6];

    ./linux/dev/include/linux/fs.h:304:5: error: unknown type name 'loff_t'
      304 |     loff_t f_pos;

This is a follow-up to commit
    d5e5dd3401ea0d0475aa830c2171be5b8a72f4fa
    Update configure.ac so that we don't need glibc when running ./configure.
Message-ID: <20240122075549.26207-1-janneke@gnu.org>